### ISSUE TITLE
Different code on github and crates.io.

### ISSUE THREAD

**Issue by kohlten** [ErnWong/crystalorb#21]
Hello, 

I was trying to use this library for a project I am working on. The crates.io version doesn't have the same code base, and there are several compile errors. If it were possible to update the crates.io code to the newest version in the GitHub repo, that would be awesome.

Thanks

**Comment by ErnWong** [comment]
Good point! I'll try to do a crates.io release soon-ish. (expect one or two days). Thanks!

**Comment by ErnWong** [comment]
Done, version [0.3.0](https://crates.io/crates/crystalorb/0.3.0) is out! Good luck with your project.
